version: "3.7"
services:
    b25-server:
        container_name: b25-server
        image: collelog/b25-server:latest-alpine
        networks:
            - container-link
        ports:
            - "40773:40773"
            - "40774:40774"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            TZ: Asia/Tokyo
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
        devices:
            - /dev/bus/usb # USB IC card reader
        init: true
        restart: unless-stopped

networks:
    default:
        external:
            name: bridge

    container-link:
        name: tv-recorder
        driver: bridge
