version: '3.7'
services:
    mirakurun:
        container_name: mirakurun
        image: collelog/mirakurun:2.15.2-alpine
        networks:
            - container-link
        ports:
            - "40772:40772"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mirakurun/sock:/var/run/mirakurun
            - ./mirakurun/conf:/usr/local/etc/mirakurun
            - ./mirakurun/db:/usr/local/var/db/mirakurun
        environment:
            NODE_ENV: production
            TZ: Asia/Tokyo
        cap_add:
            - SYS_NICE
            - SYS_ADMIN
        devices:
            - /dev/px4video0:/dev/px4video0
            - /dev/px4video1:/dev/px4video1
            - /dev/px4video2:/dev/px4video2
            - /dev/px4video3:/dev/px4video3
            - /dev/px4video4:/dev/px4video4
            - /dev/px4video5:/dev/px4video5
            - /dev/px4video6:/dev/px4video6
            - /dev/px4video7:/dev/px4video7
            - /dev/bus/usb # USB IC card reader
        init: true
        restart: unless-stopped

    mysql:
        container_name: epgstation-mysql
        image: collelog/mariadb:latest-10.4-alpine
        network_mode: "none"
        #networks:
        #    - container-link
        #ports:
        #    - "3306:3306"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mariadb/sock:/var/run/mysqld
            - ./mariadb/db:/var/lib/mysql
            - ./mariadb/init:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: epgstation
            TZ: Asia/Tokyo
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --performance-schema=false --expire_logs_days=1
        init: true
        restart: unless-stopped

    epgstation:
        container_name: epgstation
        image: collelog/epgstation:latest-alpine-amd64
        networks:
            - container-link
        ports:
            - "8888:8888"
            - "8889:8889"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mirakurun/sock:/var/run/mirakurun
            - ./mariadb/sock:/var/run/mysqld
            - ./epgstation/config:/opt/epgstation/config
            - ./epgstation/data:/opt/epgstation/data
            - ./epgstation/thumbnail:/opt/epgstation/thumbnail
            - ./epgstation/logs:/opt/epgstation/logs
            - ./recorded:/opt/epgstation/recorded
        environment:
            TZ: Asia/Tokyo
        depends_on:
           - mirakurun
           - mysql
        init: true
        restart: unless-stopped

networks:
    default:
        external:
            name: bridge

    container-link:
        name: tv-recorder
        driver: bridge
