version: "3.7"

x-devices-hardware_acceleration: &custom-devices-hardware_acceleration
    devices:
        # VAAPI
#        - /dev/dri
        # RPi MMAL
#        - /dev/vcsm
        # RPi OpenMax
#        - /dev/vchiq
        # RPi V4L2
#        - /dev/video10
#        - /dev/video11
#        - /dev/video12

x-service: &default-service
    logging:
        driver: json-file
        options:
            max-size: "10m"
            max-file: "5"
    init: true

x-environment: &default-environment
    TZ: Asia/Tokyo

x-network: &default-network
    networks:
        - container-link

x-network-host: &custom-network-host
    network_mode: "host"

x-network-non: &custom-network-none
    network_mode: "none"


services:
    xteve:
        <<: *default-service
        <<: *custom-network-host
        container_name: xteve
        image: collelog/xteve:latest-alpine
        ports:
            - "34400:34400"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./xteve/conf:/etc/opt/xteve
            - ./xteve/temp:/tmp/xteve
        environment:
            <<: *default-environment
        restart: unless-stopped

    jellyfin:
        <<: *default-service
        <<: *custom-network-host
#devices-ha#        <<: *custom-devices-hardware_acceleration
        container_name: jellyfin
        image: linuxserver/jellyfin:latest
        ports:
            - "8096:8096"
            - "8920:8920" # optional
            - "7359:7359/udp" #optional
            - "1900:1900/udp" #optional
        volumes:
            - ./jellyfin/conf:/config
            - ./jellyfin/cache:/cache
            - ./recorded:/media/video
        environment:
            <<: *default-environment
        restart: unless-stopped


networks:
    default:
        external:
            name: bridge
