epg:
  cache-dir: /var/lib/mirakc/epg

server:
  addrs:
    - unix: /var/run/mirakurun/mirakurun.sock

  stream-max-chunks: 6000
  stream-chunks-size: 32768

channels:
  - name: MX
    type: GR
    channel: '16'
  - name: CX
    type: GR
    channel: '21'
  - name: TBS
    type: GR
    channel: '22'
  - name: TX
    type: GR
    channel: '23'
  - name: EX
    type: GR
    channel: '24'
  - name: NTV
    type: GR
    channel: '25'
  - name: ETV
    type: GR
    channel: '26'
  - name: NHK
    type: GR
    channel: '27'
  - name: BS-EX
    type: BS
    channel: BS01_0
  - name: BS-TBS
    type: BS
    channel: BS01_1
  - name: BS-TX
    type: BS
    channel: BS01_2
  - name: BS03_0
    type: BS
    channel: BS03_0
  - name: BSP
    type: BS
    channel: BS03_1
  - name: BS03_2
    type: BS
    channel: BS03_2
  - name: BS05_0
    type: BS
    channel: BS05_0
  - name: BS05_1
    type: BS
    channel: BS05_1
  - name: BS07_0
    type: BS
    channel: BS07_0
    disabled: true
  - name: BS07_1
    type: BS
    channel: BS07_1
    disabled: true
  - name: BS07_2
    type: BS
    channel: BS07_2
    disabled: true
  - name: BS11
    type: BS
    channel: BS09_0
  - name: BS09_1
    type: BS
    channel: BS09_1
  - name: BS12
    type: BS
    channel: BS09_2
  - name: BS11_0
    type: BS
    channel: BS11_0
  - name: BS11_1
    type: BS
    channel: BS11_1
  - name: OUJ
    type: BS
    channel: BS11_2
  - name: BS-NTV
    type: BS
    channel: BS13_0
  - name: BS-CX
    type: BS
    channel: BS13_1
  - name: BS13_2
    type: BS
    channel: BS13_2
  - name: BS1
    type: BS
    channel: BS15_0
  - name: BS15_1
    type: BS
    channel: BS15_1
  - name: BS17_0
    type: BS
    channel: BS17_0
    disabled: true
  - name: BS17_1
    type: BS
    channel: BS17_1
    disabled: true
  - name: BS17_2
    type: BS
    channel: BS17_2
    disabled: true
  - name: BS19_0
    type: BS
    channel: BS19_0
  - name: BS19_1
    type: BS
    channel: BS19_1
  - name: BS19_2
    type: BS
    channel: BS19_2
  - name: BS21_0
    type: BS
    channel: BS21_0
  - name: BS21_1
    type: BS
    channel: BS21_1
  - name: BS21_2
    type: BS
    channel: BS21_2
  - name: BS23_0
    type: BS
    channel: BS23_0
  - name: BS23_1
    type: BS
    channel: BS23_1
  - name: BS23_2
    type: BS
    channel: BS23_2
  - name: CS2
    type: CS
    channel: CS2
  - name: CS4
    type: CS
    channel: CS4
  - name: CS6
    type: CS
    channel: CS6
  - name: CS8
    type: CS
    channel: CS8
  - name: CS10
    type: CS
    channel: CS10
  - name: CS12
    type: CS
    channel: CS12
  - name: CS14
    type: CS
    channel: CS14
  - name: CS16
    type: CS
    channel: CS16
  - name: CS18
    type: CS
    channel: CS18
  - name: CS20
    type: CS
    channel: CS20
  - name: CS22
    type: CS
    channel: CS22
  - name: CS24
    type: CS
    channel: CS24

tuners:
  - name: PX4-S1
    types: [BS,CS]
    command: >-
      recpt1 --b25 --device /dev/px4video0 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-S2
    types: [BS,CS]
    command: >-
      recpt1 --b25 --device /dev/px4video1 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T1
    types: [GR]
    command: >-
      recpt1 --b25 --device /dev/px4video2 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T2
    types: [GR]
    command: >-
      recpt1 --b25 --device /dev/px4video3 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-S3
    types: [BS,CS]
    command: >-
      recpt1 --b25 --device /dev/px4video4 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-S4
    types: [BS,CS]
    command: >-
      recpt1 --b25 --device /dev/px4video5 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T3
    types: [GR]
    command: >-
      recpt1 --b25 --device /dev/px4video6 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T4
    types: [GR]
    command: >-
      recpt1 --b25 --device /dev/px4video7 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-S5
    types: [BS,CS]
    command: >-
      recpt1 --b25 --device /dev/px4video8 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-S6
    types: [BS,CS]
    command: >-
      recpt1 --b25 --device /dev/px4video9 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-T5
    types: [GR]
    command: >-
      recpt1 --b25 --device /dev/px4video10 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-T6
    types: [GR]
    command: >-
      recpt1 --b25 --device /dev/px4video11 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-S7
    types: [BS,CS]
    command: >-
      recpt1 --b25 --device /dev/px4video12 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-S8
    types: [BS,CS]
    command: >-
      recpt1 --b25 --device /dev/px4video13 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-T7
    types: [GR]
    command: >-
      recpt1 --b25 --device /dev/px4video14 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-T8
    types: [GR]
    command: >-
      recpt1 --b25 --device /dev/px4video15 {{channel}} {{duration}} -
    disabled: true
