epg:
  cache-dir: /var/lib/mirakc/epg

server:
  addrs:
    - unix: /var/run/mirakurun/mirakurun.sock

channels:
  - name: NHK総合・東京
    type: GR
    channel: 27
  - name: NHKEテレ東京
    type: GR
    channel: 26
  - name: 日テレ
    type: GR
    channel: 25
  - name: TBS
    type: GR
    channel: 22
  - name: フジテレビ
    type: GR
    channel: 21
  - name: テレビ朝日
    type: GR
    channel: 24
  - name: テレビ東京
    type: GR
    channel: 23
  - name: TOKYO MX
    type: GR
    channel: 16
  - name: NHK BS1
    type: BS
    channel: BS15_0
  - name: NHK BSプレミアム
    type: BS
    channel: BS03_1
  - name: BS日テレ
    type: BS
    channel: BS13_0
  - name: BS朝日
    type: BS
    channel: BS01_0
  - name: BS-TBS
    type: BS
    channel: BS01_1
  - name: BSテレ東
    type: BS
    channel: BS01_2
  - name: BSフジ
    type: BS
    channel: BS13_1
  - name: WOWOWプライム
    type: BS
    channel: BS03_0
  - name: WOWOWライブ
    type: BS
    channel: BS05_0
  - name: WOWOWシネマ
    type: BS
    channel: BS05_1
  - name: スター・チャンネル1
    type: BS
    channel: BS09_1
  - name: スター・チャンネル2/スター・チャンネル3
    type: BS
    channel: BS15_1
  - name: BS11
    type: BS
    channel: BS09_0
  - name: TwellV
    type: BS
    channel: BS09_2
  - name: 放送大学 BS1/放送大学 BS2
    type: BS
    channel: BS11_1
  - name: グリーンチャンネル
    type: BS
    channel: BS19_0
  - name: BSアニマックス
    type: BS
    channel: BS13_2
  - name: BSスカパー!
    type: BS
    channel: BS11_0
  - name: J SPORTS 1
    type: BS
    channel: BS19_1
  - name: J SPORTS 2
    type: BS
    channel: BS19_2
  - name: J SPORTS 3
    type: BS
    channel: BS21_1
  - name: J SPORTS 4
    type: BS
    channel: BS21_2
  - name: BS釣りビジョン
    type: BS
    channel: BS23_0
  - name: シネフィルWOWOW
    type: BS
    channel: BS21_0
  - name: 日本映画専門チャンネル
    type: BS
    channel: BS23_1
  - name: ディズニー・チャンネル
    type: BS
    channel: BS03_2
  - name: ショップチャンネル/東映チャンネル/Mnet/日テレNEWS24
    type: CS
    channel: CS8
  - name: 衛星劇場/KBW WORLD/スポーツライブ+/スカチャン1
    type: CS
    channel: CS10
  - name: 映画ch・NECO/日テレG+/MONDO TV/日テレプラス
    type: CS
    channel: CS24
  - name: ザ・シネマ/ファミリー劇場/スーパー！ドラマTV/ヒストリーチャンネル
    type: CS
    channel: CS14
  - name: ムービープラス/ゴルフネットワーク/チャンネル銀河/女性ch／LaLa
    type: CS
    channel: CS18
  - name: スカイA/時代劇専門ch/エンタメ～テレ/MTV
    type: CS
    channel: CS4
  - name: GAORA/エムオン！/キッズステーション/ナショナルジオグラフィック
    type: CS
    channel: CS12
  - name: SKY STAGE/AXN海外ドラマ/AXNミステリー/スペシャプラス/AT-X/BBCワールドニュース
    type: CS
    channel: CS16
  - name: ホームドラマch/ミュージック・エア/歌謡ポップスch/カートゥーン/ディスカバリーチャンネル/アニマルプラネット/CNNj/囲碁・将棋チャンネル
    type: CS
    channel: CS6
  - name: TBSチャンネル1/テレ朝チャンネル1/テレ朝チャンネル2/ディズニージュニア
    type: CS
    channel: CS2
  - name: QVC/TBSチャンネル2/FOX/TBS NEWS
    type: CS
    channel: CS22
  - name: フジテレビONE/フジテレビTWO/フジテレビNEXT/スペースシャワーTV
    type: CS
    channel: CS20

tuners:
  - name: PX4-S1
    types: [BS,CS]
    command: >-
      recpt1 --device /dev/px4video0 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-S2
    types: [BS,CS]
    command: >-
      recpt1 --device /dev/px4video1 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T1
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video2 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T2
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video3 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-S3
    types: [BS,CS]
    command: >-
      recpt1 --device /dev/px4video4 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-S4
    types: [BS,CS]
    command: >-
      recpt1 --device /dev/px4video5 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T3
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video6 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T4
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video7 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-S5
    types: [BS,CS]
    command: >-
      recpt1 --device /dev/px4video8 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-S6
    types: [BS,CS]
    command: >-
      recpt1 --device /dev/px4video9 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-T5
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video10 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-T6
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video11 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-S7
    types: [BS,CS]
    command: >-
      recpt1 --device /dev/px4video12 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-S8
    types: [BS,CS]
    command: >-
      recpt1 --device /dev/px4video13 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-T7
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video14 {{channel}} {{duration}} -
    disabled: true

  - name: PX4-T8
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video15 {{channel}} {{duration}} -
    disabled: true

filters:
  decode-filter:
    command: arib-b25-stream-test
