# libarib25, recpt1, timezone
FROM alpine:3.12 AS recpt1-build

RUN set -eux
RUN apk upgrade --update
RUN apk add --no-cache ca-certificates curl git gcc g++ make cmake autoconf automake pcsc-lite-dev tzdata

RUN mkdir -p /build/libarib25
WORKDIR /build/libarib25
RUN curl -fsSL https://github.com/stz2012/libarib25/tarball/master \
	| tar -xz --strip-components=1
RUN cmake .
RUN make install

WORKDIR /build
RUN curl -fsSL https://github.com/stz2012/recpt1/tarball/master \
	| tar -xz --strip-components=1
WORKDIR /build/recpt1
RUN ./autogen.sh
RUN ./configure --prefix=/usr/local --enable-b25
RUN make -j $(nproc)
RUN make install


# arib-b25-stream-test
FROM node:14.2.0-alpine3.12 AS arib-b25-stream-test-build

RUN apk upgrade --update
RUN apk add --no-cache gcc g++ make libc-dev pcsc-lite-dev pkgconfig

RUN npm install arib-b25-stream-test -g --unsafe


# mirakurun-build
FROM node:14.2.0-alpine3.12 AS mirakurun-build

ENV DOCKER="YES"

RUN npm install mirakurun@2.15.2 -g --unsafe-perm --production
RUN sed -i -e 's/--max_old_space_size=512/--max_old_space_size=1024/g' /usr/local/lib/node_modules/mirakurun/package.json


# final image
FROM node:14.2.0-alpine3.12
LABEL maintainer "collelog <collelog.cavamin@gmail.com>"

EXPOSE 40772
ENV LD_LIBRARY_PATH=/usr/local/lib64
ENV DOCKER="YES"

# timezone
COPY --from=recpt1-build /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# libarib25
COPY --from=recpt1-build /usr/local/include/arib25 /usr/local/include/arib25
COPY --from=recpt1-build /usr/local/bin/b25 /usr/local/bin/b25
COPY --from=recpt1-build /usr/local/lib64/libarib25.a /usr/local/lib64/libarib25.a
COPY --from=recpt1-build /usr/local/lib64/libarib25.so.0.2.5 /usr/local/lib64/libarib25.so.0.2.5
COPY --from=recpt1-build /usr/local/lib64/pkgconfig/libarib25.pc /usr/local/lib64/pkgconfig/libarib25.pc

# recpt1
COPY --from=recpt1-build /usr/local/bin/recpt1 /usr/local/bin/recpt1

# arib-b25-stream-test
COPY --from=arib-b25-stream-test-build /usr/local/lib/node_modules/arib-b25-stream-test /usr/local/lib/node_modules/arib-b25-stream-test

# mirakurun
COPY --from=mirakurun-build /usr/local/lib/node_modules/mirakurun /usr/local/lib/node_modules/mirakurun


COPY services.sh /usr/local/bin

RUN set -eux && \
	apk upgrade --update && \
	apk add --no-cache ccid libstdc++ pcsc-lite pcsc-lite-libs && \
	\
	# timezone
	echo "Asia/Tokyo" > /etc/timezone && \
	\
	# libarib25
	ln -sf /usr/local/lib64/libarib25.so.0.2.5 /usr/local/lib64/libarib25.so.0 && \
	ln -sf /usr/local/lib64/libarib25.so.0 /usr/local/lib64/libarib25.so && \
	\
	# arib-b25-stream-test
	ln -sf /usr/local/lib/node_modules/arib-b25-stream-test/bin/b25 /usr/local/bin/arib-b25-stream-test && \
	\
	# cleaning
	npm cache verify && \
	rm -rf /tmp/* ~/.npm /var/cache/apk/* && \
	\
	chmod 755 /usr/local/bin/services.sh

WORKDIR /usr/local/lib/node_modules/mirakurun

ENTRYPOINT /usr/local/bin/services.sh
